### ISSUE TITLE
Add integration of Diff-Tools, e.g. FileMerge

### ISSUE THREAD

**Issue by hklindworth** [swisspol/CompareFolders#10]
It would be very helpful, if I could compare the differences between two files in an external diff viewer.

For example adding a button below the file details: Compare in Diff viewer

**Comment by snitkjaer** [comment]
I agree with that! I would really like Sublime text integration to compare file content

**Comment by hackingtosh** [comment]
Hey what about this issue, its from 2014/2015, when it will be built-in? I also would really like a filemerge (or something else) integration.
