### ISSUE TITLE
Not all subfolders being searched

### ISSUE THREAD

**Issue by Doug183** [swisspol/CompareFolders#14]
1) Sub folders cause inconsistent feedback to users about what is missing.  I am finding it a little inconsistent to test, but here is one example that I can repeat.

1a) External hard drive with 10 folders. 
1b) Copy these to a different drive and into a folder called "Happy"
1c) Move 1 folder out of "Happy".
1d) Compare the original external drive with the folder "Happy".
1e) In Compare Folder, The External Hard drive pane will not show the missing folder at all, nor any of its contents.

2a) Compare any two completely different folder and the program will just two show blank white windows.  Picking new folders, that are identical will also result in blank white screens.  Only fix is to quit and re-start Compare Folders.

I like this program and was about to buy the checksum version as I copy a lot of media from external drives to my archive server, but it needs to be more robust and trustworthy before I commit.

(My tests were done both over the server and on internal folders.)

Thanks Doug

**Comment by swisspol** [comment]
What OS X version do you have and what are these hard drives formatted with? Are they both HFS+?

**Comment by Doug183** [comment]
10.8.5

Initially I was comparing NTFS to an AFP ZFS share.  However, here are two tests I just ran on HFS+ volumes.  

0) Made a folder.
1) Duplicated a folder in HFS+.  
1a) Compared the duplicate folders - shot1
2) Created a completely new folder on an another internal HD. Folder is completely empty. (HFS+ as well)
3) Quit out of Compare Folder
4) Compared the Original Folder to the empty one.  White screen. - shot2








Here is a second test.  

1) Original Folder still the same
2) Second folder has only two items in it. Its on older video file folder (see pic of 40500)
3) The results (image with all the red)  makes no sense at all.  Duplicate files on the right.  Nothing on the left.

**Comment by swisspol** [comment]
Looks like the screenshots didn't go through. Can you reupload them? Thanks!

**Comment by swisspol** [comment]
I see you must have tried to send the images as part of the email. This is not supported with GitHub issues: you have to use the web interface to add the images (you can simply copy-paste them in).

Or just re-send your email to info@pol-online.net and I'll add them in.

When you take the screenshots, please provide the entire window include the settings area.

**Comment by swisspol** [comment]
Closing since this hasn't been updated in a while.
