### ISSUE TITLE
Filenames incorrectly match "01" and "1"

### ISSUE THREAD

**Issue by daniel-toman** [swisspol/CompareFolders#15]
I found what appears to be a small error in the file matching algorithm. 

I have a file called 22719-04.jpg in folder A, and another file called 22719-4.jpg in folder B. The file 22719-4.jpg is also in folder A. 

Folder A | Folder B
----------- | ------------
22719-04.jpg | 22719-4.jpg
22719-4.jpg | 

The program identifies 22719-04.jpg and 22719-4.jpg as two different versions of the same file. However they are totally different files. 22719-04.jpg should be recognized as a newly added file, and the file 22719-4.jpg should be shown as identical in both folders.

Folder A | Folder B
----------- | ------------
22719-04.jpg | 
22719-4.jpg | 22719-4.jpg

<img width="1269" alt="compare-folders-bug-1" src="https://cloud.githubusercontent.com/assets/1903582/12408655/696ffd26-be17-11e5-8f7c-386020bf8eaa.png">
<img width="1269" alt="compare-folders-bug-2" src="https://cloud.githubusercontent.com/assets/1903582/12408657/698e8bba-be17-11e5-854b-edacfd4fd14d.png">

**Comment by swisspol** [comment]
Thanks for reporting this issue: the problem is here:
https://github.com/swisspol/DirectoryScanner/blob/master/DirectoryScanner/DirectoryScanner.m#L91

**Comment by swisspol** [comment]
The next version of Compare Folders (1.1.4) should fix this bug hopefully.
