### ISSUE TITLE
Status / Progress Bar?

### ISSUE THREAD

**Issue by Peterjbdk** [swisspol/CompareFolders#16]
How can I tell whether the app is actually working, or not, or stalled?

MAC OSX El Capitan 10.11.2 -  two large folders on an NAS drive. Activity Monitor shows small (2.6%) CPU usage.

![screen shot 2016-01-19 at 09 33 02](https://cloud.githubusercontent.com/assets/16774754/12414791/add5ddb4-be8f-11e5-8a2a-6a18d78f9080.png)

Console readout:
![screen shot 2016-01-19 at 09 38 12](https://cloud.githubusercontent.com/assets/16774754/12414894/70d0c7fc-be90-11e5-824e-1a35d2f0e5a9.png)

**Comment by swisspol** [comment]
The infinite progress bar under "compare again" should animate. In the recent versions of OS X they made it very subtle though.

**Comment by Peterjbdk** [comment]
Thank you for the info.

I believe that it has finished now, but how do I interpret the results?

I have list of files and folders that appear identical; does this mean that they are identical and I have no problems?

**Comment by swisspol** [comment]
Sounds like it :smile:
