### ISSUE TITLE
File Checksums problem

### ISSUE THREAD

**Issue by hoffmanjay** [swisspol/CompareFolders#17]
I purchased the file checksums add-on in the Apple app store. It didn't seem to download or be activated. I've tried the "Restore Purchases..." menu item from the Compare Folders "Store" menu and it asks for my Apple password and seems to log in, but still doesn't do anything. I sometimes get an error message from Compare Folders: "In-App Purchase error!"

Any ideas of what could be wrong?

**Comment by swisspol** [comment]
I would try deleting the app, restarting the computer, then re-install it and doing restore purchase one more time.

If that doesn't work, launch Console app and search for "Compare Folders" and please copy-paste whatever you find in here.

**Comment by hoffmanjay** [comment]
Thanks for your help. I deleted the app, rebooted and reinstalled from the app store purchases. When I ran the app, the file checksum feature was active - I didn’t have to restore purchases. Thanks again.


On Mar 10, 2016, at 5:00 PM, Pierre-Olivier Latour <notifications@github.com<mailto:notifications@github.com>> wrote:


I would try deleting the app, restarting the computer, then re-install it and doing restore purchase one more time.

If that doesn't work, launch Console app and search for "Compare Folders" and please copy-paste whatever you find in here.

**Comment by swisspol** [comment]
Great to hear :)
