### ISSUE TITLE
Permission problems - Failed opening directory

### ISSUE THREAD

**Issue by edzusviksna** [swisspol/CompareFolders#19]
**Failed opening directory**
I have got permission problems with folders on my mac. Not sure, if problem is just in app or whole system, but sure I am, that I can't get rid of it.
![screen shot 2016-04-19 at 19 28 25](https://cloud.githubusercontent.com/assets/18557493/14647286/b6ad2410-0665-11e6-9e25-c350687ce7af.png)

This permission problem is with any folder on computer.

Google doesn't show solution for permission problems. On _Get Info_ section Read&Write are allowed.

**Comment by swisspol** [comment]
> I have got permission problems with folders on my mac.

This has no reason to be a Compare Folders issue: the app is just trying to open a folder to see its contents, but OS X doesn't authorize it.

> This permission problem is with any folder on computer.

Are you sure about this? What if you compare 2 directories inside your home directory?

**Comment by edzusviksna** [comment]
@swisspol Good idea, I tried to compare folders on desktop, there were no problems with permissions. Yes, there are problems with external drives.
Tried to do this - https://discussions.apple.com/thread/3687931?tstart=0 didn't work out. Still permission problems.
