### ISSUE TITLE
Fails to compare when using CDROM as source

### ISSUE THREAD

**Issue by daniep01** [swisspol/CompareFolders#21]
I would like to compare a CDROM with a folder on my computer in order to verify the files have copied correctly and accurately. When doing this I always get an error 'Failed retrieving file system info' - 'Invalid argument'. OS X 10.9.5, MacPro Early 2009.

**Comment by swisspol** [comment]
Do you know what is the format of the CDROM is? Compare Folder only works with HFS+ volumes.

**Comment by swisspol** [comment]
Closing since no update in a while.
