### ISSUE TITLE
what does the color mean?

### ISSUE THREAD

**Issue by eightbits8** [swisspol/CompareFolders#22]
i tried to find help but couldnt, and im wondering what does the colors means?

which files/folders are matching and which isnt?

**Comment by swisspol** [comment]
Red means different content, orange means different properties and green means all identical.

**Comment by eightbits8** [comment]
thanks for the fast response, do you think you can add labels or something for color blinds?
i know that this sounds funny but im color blind myself and i cant see the difference between the red and orange

**Comment by swisspol** [comment]
Ah, I totally understand your problem. Unfortunately, I'm not actively working on this project anymore, sorry (and the app works as-is, so there's no need for updates anyway).

**Comment by eightbits8** [comment]
unfortunately this wasnt mentioned when i purchased the checksum feature for $4.99, i would like to get a refund since the product doesnt even have a help and on top of that you have stopped working on it.

let me know how i can request for a refund, thanks

**Comment by swisspol** [comment]
Note that I didn't say that I "have stopped working on it", but that "I'm not *actively* working on this project ". Compare Folders is fully functional and people are quite happy with it. It's just that since it does its job well, there are no plans to add *new features*.

If you want a refund, you have to request it from the App Store - Apple does not provide developers any way to initiate them.

**Comment by eightbits8** [comment]
i disagree on the functionality thing since i cannot tell the reason behind the file/folder isnt identical specifically when the checksum feature is enabled.

i have requested a refund. 

Thanks for your quick response.

**Comment by danielsharvey** [comment]
+1 on this question and suggestions for improvement.

It would highly helpful to have one/all of the following:

1. Simple help outlining the colour key: "Red means different content, orange means different properties and green means all identical."
1. In the detail box at the bottom left/right of the window a status: "Content different" / "Properties different" / "Content & properties identical".

Thanks
