### ISSUE TITLE
Exclude File extensions

### ISSUE THREAD

**Issue by Mr-Tiki** [swisspol/CompareFolders#23]
Hi!
I just discovered CompareFolders. Here's my problem: 
I need to compare to folders containing a large amount of images. The problem: one folder contains TIFFs, the other one JPGs.  I just need to compare the actual file names in search for missing files. 
Can I actually do that or couuld you add this feature in future versions?

Cheers,
Dan

**Comment by swisspol** [comment]
This is not a feature that compare folders has nor would it be in a future version, sorry.
