### ISSUE TITLE
Problems with case sensitive folders/volumes

### ISSUE THREAD

**Issue by Zorfware** [swisspol/CompareFolders#28]
I'll let the picture speak for itself.

<img width="1112" alt="screen shot 2017-04-16 at 12 04 00" src="https://cloud.githubusercontent.com/assets/27618861/25070401/a73360f8-229d-11e7-8438-8c6f34ead5ef.png">

**Comment by swisspol** [comment]
Thanks for reporting this. I don't think case-sensitive volumes will ever be supported though.
