### ISSUE TITLE
Purchased file checksums and now the app won't open and is useless.

### ISSUE THREAD

**Issue by jldart** [swisspol/CompareFolders#33]
App wouldn't open after purchase.  Deleted and re-installed.  Same result.  Restarted computer, signed out and back in to app store, did safe re-boot, deleted and re-installed multiple times with same result.  Either says app is damaged or get and endless stream of unsuccessful login dialogs for my apple ID.

I have no problems with any other apps or the app store and did not have a problem with app until I purchased the file checksums in app purchase.

Now you have my money and I have nothing.  Is there any solution?  Apple support says it is an app problem.  Thanks.

**Comment by swisspol** [comment]
Hi! A couple people have reported the same issue. It’s clearly related to the App Store app signing verification but I have no idea what’s going on yet. In the meantime I suggest you ask the App Store for a refund. Sorry about that :/

Please continue discussion in this other issue: #32.

PS: this may be related to Mac apps using in app purchases.
