### ISSUE TITLE
Add support for copying files by dragging

### ISSUE THREAD

**Issue by mhngithub** [swisspol/CompareFolders#35]
Your utility brought to my attention that the finder , even though is set to show hidden files, does not show a file existing on a DVD named ".DS_Store".
Naturally, when copying the DVD, that file does not get copied. It "Would be great" if I could drag it from where it exists (In your dialog window) and copy to the destination drive.

Thank ever so much
<img width="1388" alt="screen shot 2017-12-14 at 6 07 19 pm" src="https://user-images.githubusercontent.com/20509501/34023428-bc7bf9be-e0f9-11e7-88f9-cee4073aeabd.png">

**Comment by danielsharvey** [comment]
+1
