### ISSUE TITLE
Difficult to tell that file content is identical

### ISSUE THREAD

**Issue by danielsharvey** [swisspol/CompareFolders#36]
I have the following file, which I have confirmed via "diff" to hold identical content.

The file shows as red in the list. How do I know from the display that the checksum shows the file contents as identical?

![image](https://user-images.githubusercontent.com/12858056/36577796-6b668eea-1894-11e8-9f1f-9034dadb9fc8.png)

Thanks

**Comment by swisspol** [comment]
The UI actually works differently: the info section at the bottom will not indicate if everything is the same except the byte content of the files (detected through hashing). This is instead shown in the table above with the file being highlight in red.
