### ISSUE TITLE
CompareFolders incorrectly shows "Last Modified" dates changed after Finder copy

### ISSUE THREAD

**Issue by brianaweeks1** [swisspol/CompareFolders#37]
I copied the entire contents of one flash drive to a freshly-formatted flash drive. For about 1/3 of the items, 'Compare Folders' showed a modification date for the files that was the date/time of the Finder copy. And for a small handful of the files, the "Creation Date" was also changed to the date/time of the Finder copy. Now, when comparing the two flash drives in the Finder, the target flash drive showed the same creation and last-modified dates as the original. QUESTION: WHY is 'Compare Folders' showing these creation and modification dates as being changed, when they weren't modified, they were just finder-copied? All the files were finder-copied about 9 p.m. Feb 25, 2018

![screen shot 2018-02-26 at 9 21 24 am](https://user-images.githubusercontent.com/26388825/36683299-3e449066-1aeb-11e8-89fc-aa11168d1efa.png)
![screen shot 2018-02-26 at 9 20 57 am](https://user-images.githubusercontent.com/26388825/36683329-49e2591c-1aeb-11e8-9dba-b1446586d779.png)

**Comment by swisspol** [comment]
I'm afraid I can't really say. If CompareFolders reports the file creation / modification dates as different, then they are. Who knows what the Finder did in this case. Also be aware that Compare Folders does not really support volumes / disks that are not formatted in HFS+ which may be the case for your flash drives.

**Comment by brianaweeks1** [comment]
Dear Pierre-Olivier Latour
1) Thanks so much for the rapid reply!
2) Yes, the flash drives were FAT32. If CF doesn’t support anything other than HFS+, then that might be the problem right there.
3) Does CF support APFS? If not, is it planned for any release date?
Thanks
Brian Weeks



On Feb 26, 2018, at 4:06 PM, Pierre-Olivier Latour <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm afraid I can't really say. If CompareFolders reports the file creation / modification dates as different, then they are. Who knows what the Finder did in this case. Also be aware that Compare Folders does not really support volumes / disks that are not formatted in HFS+ which may be the case for your flash drives.

**Comment by swisspol** [comment]
> Does CF support APFS?

I haven't tested yet, but haven't heard anyone reporting any problem. This new file system is supposed to be fully compatible with HFS+ so I'm not expecting anything breaking.

**Comment by brianaweeks1** [comment]
Thanks.
BW



On Feb 26, 2018, at 4:57 PM, Pierre-Olivier Latour <notifications@github.com<mailto:notifications@github.com>> wrote:


Does CF support APFS?

I haven't tested yet, but haven't heard anyone reporting any problem. This new file system is supposed to be fully compatible with HFS+ so I'm not expecting anything breaking.
