### ISSUE TITLE
What does the Resource Size file attribute means? 

### ISSUE THREAD

**Issue by mlemos** [swisspol/CompareFolders#42]
I'm comparing two folders and the unique difference in that one specific file has different "Resource Size" values between folders. In one folder the value is 286 bytes and in the other, it is 0 bytes. But the files seem to be exactly the same. 

I'm not sure on how to correctly interpret the "Resource Size" difference.

Thanks in advance for any help!

**Comment by swisspol** [comment]
Hi!

For historical reasons Mac files can store two "data streams": a regular
one like on all OSes or non Mac files systems and a "resource" one which is
a unique concept that dates back to MacOS from more than 20 years ago. They
are being deprecated and will eventually go entirely away. This will take
years though.

Resources data streams used to be used to store some file metadata. More
likely than not the difference you are observing doesn't matter.

You can Google for "Mac resource forks" if you want more information.

**Comment by mlemos** [comment]
Hi @swisspol , thanks a lot for your answer.
I was really puzzled about that and all my searches around "Resource Size" were leading to nowhere.
I had stumble on the resource forks but didn't realize they were connected.
Best,
Manoel
