### ISSUE TITLE
Add support for source folder drag & drop

### ISSUE THREAD

**Issue by marka4** [swisspol/CompareFolders#9]
I have some other changes for new features.  They are listed in decreasing priority for me.
1) Provide drag and drop functionality for specifying the folders to compare.  Using a browse button is way too many mouse clicks.
2) Add an option to trigger a difference if labels (or tags with Mavericks) are different.
3) ACLs
4) Extended attributes
For requests 3 and 4, you could simply say that there is a difference but it would be better to list them.
For request 2, you could just have a series of colored dots.

Thank you,
Mark

**Comment by paulmoons** [comment]
Firstly, thanks @swisspol for writing this. Secondly, please consider adding drag and drop. This feature alone would make it infinitely more useful.
